### ISSUE TITLE
v0.0.7015.27853-pre doesn't install any website files

### ISSUE THREAD

**Issue by willseward** [svenkle/nuget-server#10]
Using both the installer and the CLI version on v0.0.7x fail on my system (Windows Server 2016) because none of the files under `.\Host\Website\` are present, excluding `.\Host\Website\Configuration\`.

I've confirmed that the previous version of the software *do* include these files properly.

**Comment by svenkle** [comment]
Looks like the last update wiped out the copy post build step. I'll push up a revised version later today.

**Comment by svenkle** [comment]
I've uploaded a new CLI version for you to try out. If that succeeds I'll update the AIP installer and close this issue.

**Comment by willseward** [comment]
@svenkle That release did include the website files, but for some reason I can only get 5 or 6 requests out of it before it locks up.

I'll open another issue for that issue, if I can't get our Cassini-based install back online.
