### ISSUE TITLE
Nuget feed hangs

### ISSUE THREAD

**Issue by ghost** [svenkle/nuget-server#2]
nuget server hangs after almost each restore. I have default configuration

**Comment by svenkle** [comment]
Hi @aleibowitz,

Can you please provide more information to help troubleshoot? 

Are you running *nuget restore* from the command line?
Are you using any other nuget feeds eg. Nuget.org?
How many packages have you deployed to the repository?
What changes have you applied to your nuget.config file either in your current solution or globally on your machine?

Regards,
Luke

**Comment by svenkle** [comment]
I'm going to go ahead and close this as you haven't replied.
