### ISSUE TITLE
Authentication while consuming packages

### ISSUE THREAD

**Issue by gowthamrang** [svenkle/nuget-server#5]
I am  a noob trying to set up a private feed. I want to allow only users with the right credentials to view/consume nuget packages i push to this feed.  Is this currently possible with this application ?

**Comment by svenkle** [comment]
@gowthamrang this package is a IIS hosted wrapper for the standard NuGet Server feed [here](https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server). As far as I'm aware it doesn't support authentication - only API keys for pushing packages to the feed.

That being said, you should be able to use basic authentication in IIS express by editing the applicationhost.config file.

**Comment by gowthamrang** [comment]
Thank you! 
This is probably not the right place to post this question. Anyway,
Where can I set the username password after enabling the windows authentication ?

**Comment by svenkle** [comment]
It's probably easier for you to use Basic Authentication over HTTPs then add a local user in the normal Windows user management snapin.
