### ISSUE TITLE
Do you have a package management function？

### ISSUE THREAD

**Issue by Varorbc** [svenkle/nuget-server#8]
For example, uploading packets, deleting packages, and other functions

**Comment by svenkle** [comment]
@Varorbc this project is a semi-self contained wrapper for [NuGet Server](https://www.nuget.org/packages/NuGet.Server/). You should be able to follow [this guide](https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference) for managing packages.

**Comment by Varorbc** [comment]
@svenkle like this
![image](https://user-images.githubusercontent.com/5714438/34513005-df567bce-f0a0-11e7-80b4-9f4692524e50.png)

**Comment by svenkle** [comment]
@Varorbc that functionality is accessible through the NuGet Server API from Microsoft (which is wrapped in my IIS Express Runner). AFAIK there isn't a "pretty" interface included that allows you to do that. You would need to build your own or use the executable linked above to manipulate the API directly. I'm not the maintainer of the NuGet Server API that's these guys [here](https://github.com/NuGet/NuGet.Server/).
