### ISSUE TITLE
IP not working as URL Path

### ISSUE THREAD

**Issue by TobiasGlaubach** [svenkle/nuget-server#9]
Hi, 
Thanks for the work, I got the server up and running locally, was able to push my packages into it. So far so good. But when I try to access the server through the machines IP (e.G. 192.168.2.XX) I can not reach the server: 

```
Bad Request - Invalid Hostname

HTTP Error 400. The request hostname is invalid.
```

I tried starting the tool as Administrator as well. Same result. Not sure if thats an Issue, or I just can't find the proper setting, I am not very familar with running web services. Where can I configure that, if possible? 

Tobi

**Comment by svenkle** [comment]
Hi @TobiasGlaubach,

I've just tried to replicate this issue and all appears to be working for me. Can you confirm you've set the binding appropriately. `<binding protocol="http" bindingInformation=":8080:192.168.2.XX" />` where XX is your IP?

Can you also provide any steps you've taken eg. Folder Permissions, Changed location etc.

Cheers,
Luke

**Comment by TobiasGlaubach** [comment]
I had that set before, and it didn't work back then. To be sure I tested again. Turns out it works from the local machine, but any other PC in the network can't access it (I can remotedesktop to the machine though). It might be related to our Network. Let me check that first.

**Comment by TobiasGlaubach** [comment]
OK I finally got a reply from our Network and VM Admin. Our system does not seem to be the issue.

I here is all the test cases I ran:

```
Running exe with <binding protocol="http" bindingInformation=":5000:192.168.2.24" />:
--> locally (through http://192.168.2.24:5000/): OK
--> network (through http://192.168.2.24:5000/): no connection

Running exe with <binding protocol="http" bindingInformation=":5001:192.168.2.24" />:
--> locally (through http://192.168.2.24:5001/): OK
--> network (through http://192.168.2.24:5001/): no connection

Running exe with <binding protocol="http" bindingInformation=":8080:192.168.2.24" />:
--> locally (through http://192.168.2.24:8080/): OK
--> network (through http://192.168.2.24:8080/): no connection

Running exe with <binding protocol="http" bindingInformation=":5000:0.0.0.0" />:
--> startup error: Failed to register URL "http://0.0.0.0:5000/" for site "NuGetServer" application "/". Error description: Die Anforderung wird nicht unterst³tzt. (0x80070032)
HostRunnerOnExited
```

Running Minimalist python flask server as a system test on the same machine:

```
python -m flask run --host=0.0.0.0 --port=8080
--> locally (through http://192.168.2.24:8080/) : OK
--> network (through http://192.168.2.24:8080/) : OK

python -m flask run --host=0.0.0.0 --port=5000
--> locally  (through http://192.168.2.24:5000/): OK
--> network  (through http://192.168.2.24:5000/): OK

python -m flask run --host=192.168.2.24 --port=5000
--> locally  (through http://192.168.2.24:5000/): OK
--> network  (through http://192.168.2.24:5000/): OK
```

**Comment by TobiasGlaubach** [comment]
Installation path: `C:\nuget-server\SvenkleNuGetServer`
EXE path: `C:\nuget-server\SvenkleNuGetServer\Svenkle.NuGetServer.Service.exe`
User running the EXE is Admin

**Comment by Filipsi** [comment]
I have faced the same problem, this is what worked for me:

Setting HTTP protocol binding in **applicationhost.config** to
`<binding protocol="http" bindingInformation="*:8010:192.168.1.102" />`

Adding **netsh** rule via cmd
`netsh http add urlacl url=http://192.168.1.102:8010 user=Everyone`

I hope it helps.
